name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of the workflow from any
  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Authenticate via Service Account Key JSON
    # See https://github.com/google-github-actions/auth#authenticating-via-service-account-key-json-1
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'
    - id: 'upload-dags'
      name: 'Upload Airflow DAGs to GCP - Intended for use with GCP Composer Airflow'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: ./airflow/dags
        destination: ${{ vars.GCP_BUCKET_NAME  }}
