name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of the workflow from any


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run pre-commit
        run: pre-commit run --all-files

  build:
    runs-on: ubuntu-latest
    needs: pre-commit

    steps:
    - uses: actions/checkout@v3

    # Authenticate via Service Account Key JSON
    # See https://github.com/google-github-actions/auth#authenticating-via-service-account-key-json-1
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'
    - id: 'upload-dags'
      name: 'Upload Airflow DAGs to GCP - Intended for use with GCP Composer Airflow'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: ./airflow/dags
        destination: ${{ vars.GCP_BUCKET_NAME  }}
